version: '3'
services:

  # RDB
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      TZ: Asia/Tokyo
    env_file: ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql-confd:/etc/mysql/conf.d
      - ./mysql/init-sql:/docker-entrypoint-initdb.d
    tty: true
    restart: always

  # リバースプロキシ
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:8080"
    environment:
      - TZ=Asia/Tokyo
    tty: true
    restart: always

  # ワードプレス
  wordpress:
    build: wordpress
    container_name: wordpress
    depends_on:
     - mysql
    restart: always
    volumes:
      - ./wordpress/www/html:/var/www/html